import = [
    "~/.config/alacritty/themes/catppuccin_mocha.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 16
padding.y = 14

# padding.x = 10
# padding.y = 10

decorations = "none"

opacity = 0.97

option_as_alt = "Both"

[font]
normal.family = "MesloLGS Nerd Font Mono"

size = 14

[keyboard]
bindings = [
  { key = "F11", action = "ToggleFullscreen" }
]
