"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](mauve)\
$os\
$username\
[](bg:lavender fg:mauve)\
$directory\
[](fg:lavender bg:peach)\
$git_branch\
$git_status\
[](fg:peach bg:pink)\
$c\
$rust\
$golang\
$php\
$java\
$kotlin\
$ruby\
$haskell\
$python\
[](fg:pink bg:teal)\
$docker_context\
$conda\
[](fg:teal bg:surface1)\
$time\
[ ](fg:surface1)\
$line_break$character"""

palette = 'catppuccin_mocha'

[palettes.gruvbox_dark]
color_fg0 = '#fbf1c7'
color_bg1 = '#3c3836'
color_bg3 = '#665c54'
color_blue = '#458588'
color_aqua = '#689d6a'
color_green = '#98971a'
color_orange = '#d65d0e'
color_purple = '#b16286'
color_red = '#cc241d'
color_yellow = '#d79921'

[palettes.catppuccin_mocha]
color_fg0 = '#fbf1c7'
color_bg1 = '#3c3836'
color_bg3 = '#665c54'
color_blue = '#458588'
color_aqua = '#689d6a'
color_green = '#98971a'
color_orange = '#d65d0e'
color_purple = '#b16286'
color_red = '#cc241d'
color_yellow = '#d79921'

rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[os]
disabled = false
style = "bg:mauve fg:rosewater"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
show_always = true
style_user = "bg:mauve fg:rosewater"
style_root = "bg:mauve fg:rosewater"
format = '[ $user ]($style)'

[directory]
style = "fg:rosewater bg:lavender"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:peach"
format = '[[ $symbol $branch ](fg:yellow bg:peach)]($style)'

[git_status]
style = "bg:peach"
format = '[[($all_status$ahead_behind )](fg:yellow bg:peach)]($style)'

[nodejs]
symbol = ""
style = "bg:pink"
format = '[[ $symbol( $version) ](fg:red bg:pink)]($style)'

[c]
symbol = " "
style = "bg:pink"
format = '[[ $symbol( $version) ](fg:red bg:pink)]($style)'

[rust]
symbol = ""
style = "bg:pink"
format = '[[ $symbol( $version) ](fg:red bg:pink)]($style)'

[golang]
symbol = ""
style = "bg:pink"
format = '[[ $symbol( $version) ](fg:red bg:pink)]($style)'

[php]
symbol = ""
style = "bg:pink"
format = '[[ $symbol( $version) ](fg:red bg:pink)]($style)'

[java]
symbol = " "
style = "bg:pnk"
format = '[[ $symbol( $version) ](fg:red bg:pink)]($style)'

[kotlin]
symbol = ""
style = "bg:pink"
format = '[[ $symbol( $version) ](fg:red bg:pink)]($style)'

[haskell]
symbol = ""
style = "bg:pink"
format = '[[ $symbol( $version) ](fg:red bg:pink)]($style)'

[python]
symbol = ""
style = "bg:pink"
format = '[[ $symbol( $version) ](fg:red bg:pink)]($style)'

[ruby]
symbol = ""
style = "bg:pink"
format = '[[ $symbol( $version) ](fg:red bg:pink)]($style)'

[docker_context]
symbol = ""
style = "bg:teal"
format = '[[ $symbol( $context) ](fg:#83a598 bg:teal)]($style)'

[conda]
style = "bg:teal"
format = '[[ $symbol( $environment) ](fg:#83a598 bg:teal)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:surface1"
format = '[[  $time ](fg:text bg:surface1)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:color_green)'
error_symbol = '[](bold fg:color_red)'
vimcmd_symbol = '[](bold fg:color_green)'
vimcmd_replace_one_symbol = '[](bold fg:color_purple)'
vimcmd_replace_symbol = '[](bold fg:color_purple)'
vimcmd_visual_symbol = '[](bold fg:lavender)'
