return {
  -- "nomnivore/ollama.nvim",
  -- dependencies = {
  --   "nvim-lua/plenary.nvim",
  -- },
  --
  -- -- All the user commands added by the plugin
  -- cmd = { "Ollama", "OllamaModel", "OllamaServe", "OllamaServeStop" },
  --
  -- keys = {
  --   -- Sample keybind for prompt menu. Note that the <c-u> is important for selections to work properly.
  --   {
  --     "<leader>oo",
  --     ":<c-u>lua require('ollama').prompt()<cr>",
  --     desc = "ollama prompt",
  --     mode = { "n", "v" },
  --   },
  --
  --   -- Sample keybind for direct prompting. Note that the <c-u> is important for selections to work properly.
  --   {
  --     "<leader>oG",
  --     ":<c-u>lua require('ollama').prompt('Generate_Code')<cr>",
  --     desc = "ollama Generate Code",
  --     mode = { "n", "v" },
  --   },
  -- },
  --
  -- ---@type Ollama.Config
  -- opts = {
  --   -- your configuration overrides
  --   model = "gemma2",
  -- },

  -- prompts = {
  --   -- Prompt for the user to select a model
  --   Documentation_Prompt = {
  --     prompt = "Generate documentation in RDOC format $ftype for the following code: $input\n\nRespond EXACTLY in this format:\n```$ftype\n<your code>\n```",
  --     action = "insert",
  --   },
  -- },
}
